### ISSUE TITLE
Firefox add-on, Question

### ISSUE THREAD

**Issue by JKAbrams** [phixofor/unvis.it#1]
This thing suffers from a lack of a unimaginably simple Firefox add-on.
To this effect let me incite you to visit https://addons.mozilla.org/en-US/firefox/addon/unvisit/ where this has been remedied. It's currently awaiting approval from our Mozilla Add-ons overlords.

Now for my question, to build this thing I *may* have used your icons. **U mad?** :-)

To push my luck I would also like to add your wonderful illustration to the screen-shot section of the add-on.

*Thanks for your dedication to cause against the [http://idiots.blog.tro/lls](http://unvis.it/http://idiots.blog.tro/lls)!*

(Failed to find another way to contact you.)

**Comment by phixofor** [comment]
Yeah. This will have to be put on hold, as I need to rework unvisit into a database solution pretty soon. The usage is increasing, which is putting a strain on the file system.

But huge thanks for your contribution!
