### ISSUE TITLE
Default database.

### ISSUE THREAD

**Issue by k0nsl** [phixofor/unvis.it#3]
Can you provide a default database for import with the various fields already filled in? Makes setting it up speedier.

Good job on the project.

**Comment by k0nsl** [comment]
Never mind, I created the defaults manually :)

**Comment by phixofor** [comment]
I actually suck at databases, and lodjurets commit helped me with that. But it's basically 4 columns, uid, hash, body, and time. the hash is the url, and the rest is pretty self-explanatory I hope?

**Comment by k0nsl** [comment]
It is, yes. I only wanted a simple way to deploy it straight away :)

Tack!

**Comment by k0nsl** [comment]
Scratch that, seems it does not work. Can perhaps @lodjuret chime in with any comments on my table? See attached screenshot.

![unvisit-db01_k0nsl](https://cloud.githubusercontent.com/assets/2517921/6765205/3d17c040-cfd6-11e4-8a22-a3fd46ee374f.png)

Thanks for any help.

**Comment by k0nsl** [comment]
Update: I changed the type/s to the following. Does it look okay to you @lodjuret?

![unvisit-db02_k0nsl](https://cloud.githubusercontent.com/assets/2517921/6765613/8f6fa558-cfe8-11e4-90c4-68f23fbe1537.png)

**Comment by lodjuret** [comment]
Like this:
![screenshot - 2015-03-22 - 23 55 30](https://cloud.githubusercontent.com/assets/11411729/6771934/4ca84bdc-d0ef-11e4-8b60-5930eadd607b.png)

**Comment by k0nsl** [comment]
Thank you @lodjuret !
