### ISSUE TITLE
.sql file or similar to create an empty databse

### ISSUE THREAD

**Issue by lindell** [phixofor/unvis.it#5]
Would be nice to not go through the code and guess how the database are suppose to be structured.

**Comment by lindell** [comment]
Was looking at previous issues and found [this](https://github.com/phixofor/unvis.it/issues/3#issuecomment-84728918) and was thinking I'm going to recreate this myself and then push an commit with the sql file but I have some questions.

1. Is there any reason that hash is text? Should not binary be the optimal way or at least use an varchar so that the hash may be indexed in mysql?
2. Why use latin1_swedish_ci and not utf8?

**Comment by lindell** [comment]
This seems to be what is used. Maybe @lodjuret can confirm?
```
CREATE TABLE IF NOT EXISTS `cached` (
`id` int(11) NOT NULL AUTO_INCREMENT,
  `hash` text CHARACTER SET latin1 NOT NULL,
  `body` text CHARACTER SET latin1 NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) DEFAULT CHARSET=utf8;
```

**Comment by lodjuret** [comment]
yep!
