### ISSUE TITLE
Git not up to date with unvis.it

### ISSUE THREAD

**Issue by lindell** [phixofor/unvis.it#7]
Found out a small difference between the git code and the unvis.it page.
It's just the word "read" that is replaced with "share" on the site.
https://github.com/phixofor/unvis.it/blob/master/index.php#L52

This is a small change that doesn't make any difference but I was wondering if there is any other changes that is not in the repo. If there is code that is not committed and pushed it would be great to know about it.

**Comment by phixofor** [comment]
With your pull request that got merged, and is now up and running – this issue is fixed.
