### ISSUE TITLE
New Chrome extension

### ISSUE THREAD

**Issue by Cederfjard** [phixofor/unvis.it#9]
I've made a Chrome extension for Unvis.it, I thought that maybe you'd like to add it to the README:
https://chrome.google.com/webstore/detail/unvisiter/igpkaocbogccbapdaolipnlamimjjkjd
https://github.com/Cederfjard/unvisiter

I wasn't aware that there already was an extension until just now, but mine has a little more features, so perhaps it's not a total waste. :)

**Comment by phixofor** [comment]
Thank you! It works great. Adding it now!
